import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarServer from "@/components/NavbarServer";
import { Hanken_Grotesk } from "next/font/google";
import {ThemeProvider} from 'next-themes'


const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-hanken-grotesk",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hanken.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
        attribute='class'
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange 
        >
          <NavbarServer />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
